# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  lint-and-build:
    docker:
      - image: cimg/node:8.17
    steps:
      - checkout
      - docker/build:
          lint-dockerfile: true 
          image: willko/knex-repl
          path: .
          tag: 1.1.$CIRCLE_BUILD_NUM
  build-and-test:
    docker:
      - image: cimg/node:8.17
    steps:
      - checkout
      - run:
          name: Run NPM Install
          command: npm install
      - run:
          name: Build Images
          command: make
      - run:
          name: Run tests
          command: node tests/index.js
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

workflows:
  main:
    jobs:
      - lint-and-build
      - build-and-test
