# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  build-lint-and-test:
    docker:
      - image: cimg/node:8.17
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Run NPM Install
          command: npm install
      - docker/build:
          lint-dockerfile: true 
          image: willko/knex-repl
          path: .
          tag: 1.1.$CIRCLE_BUILD_NUM
      - run:
          name: Build Images
          command: |
              make
              node tests/index.js

workflows:
  main:
    jobs:
      - build-lint-and-test
