# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  build-and-test:
    docker:
      - image: cimg/node:7.8
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build Images
          command: make
      - run:
          name: Run tests
          command: node tests/index.js
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
  build-test-and-deploy:
    docker:
      - image: cimg/node:7.8
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build Images
          command: make
      - run:
          name: Run tests
          command: node tests/index.js
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      # build and push Docker image
      - run: |
          TAG=1.1.$CIRCLE_BUILD_NUM
          docker build -t willko/knex-repl:$TAG .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push CircleCI-Public/circleci-demo-docker:$TAG
workflows:
  main:
    jobs:
      - build-and-test
      # - build-test-and-deploy
