theme: jekyll-theme-slate
title: knex-repl
email: willko747@gmail.com
description: >
  converts knex code into SQL
baseurl: ""
url: "https://knex.wko.io"
github_username:  William-Olson
markdown: kramdown
